#!/usr/bin/env python3
"""patch_witw_enrich_pass3.py  --  Women in the Water, VO pass-3 CONTAINER FILL.

Fills every block to ~200s so VO lands on the grid with ~0 cumulative drift
(pauses are placed deliberately in Filmora, not inherited as block-level air).
Per-block word adds are computed from each block MEASURED words-per-second in
the pass-2 render (blocks read at different speeds), not a film average. Frozen:
beat count, order, sentence groups, phenomena, visuals -- only wording changes.

Anchor-verified against the pass-2 narration; ABORTS (no write) on any drift.
Idempotent, .pre_ backup, ASCII-only. Operates on master.csv.

    cd ~/Projects/Pipeline/sacred-dawn/projects/women-in-the-water
    python3 patch_witw_enrich_pass3.py
"""
import argparse, csv, os, sys

EDITS = {
    (1,1): ('There is a single ancient, leather-bound book most Bibles do not carry -', 'There is a single ancient, leather-bound book that most Bibles simply do not carry -'),
    (1,2): ('a book the whole ancient world of towers once knew, and lived by.', 'a book the whole ancient world of dark stone towers once knew, and lived by.'),
    (1,3): ('Its pages are written in Geez, the ancient tongue of the Ethiopian highlands -', 'Its pages are all written in Geez, the ancient sacred tongue of the Ethiopian highlands -'),
    (1,4): ('kept alive by hand, in that high place, for a thousand years.', 'kept alive by hand, in that high and distant place, for a full thousand years.'),
    (1,5): ('The name the book carries is that of a single man - Enoch -', 'The name that the book itself carries is that of a single man - Enoch -'),
    (1,6): ('the man Genesis says walked with God - and then, like light, was gone.', 'the man that Genesis says walked with God - and then, like light itself, was gone.'),
    (1,7): ('For centuries after, the rest of the world let it vanish into dust -', 'For long centuries after, the rest of the wide world let it vanish into dust -'),
    (1,8): ('buried, forgotten, and quietly cut from the canon we still carry now.', 'buried, forgotten, and quietly cut away from the canon we still carry with us now.'),
    (1,9): ('Only one distant church, blazing high on its dawn-lit cliff, kept it breathing -', 'Only one distant church, blazing high upon its steep dawn-lit cliff, kept it breathing -'),
    (1,10): ('the Ethiopian Orthodox Church, who still raise it and call it scripture today.', 'the Ethiopian Orthodox Church, who still raise it up and call it scripture to this day.'),
    (1,11): ('And here - like a storm on the horizon - the story turns strange -', 'And here - like a dark storm on the far horizon - the story turns strange -'),
    (1,12): ('because the New Testament itself reaches back across time and quotes it anyway.', 'because the New Testament itself reaches back across the years and quotes it directly anyway.'),
    (1,13): ('In one short New Testament letter, Jude borrows a line from Enoch -', 'In one short New Testament letter, a man named Jude borrows a line from Enoch -'),
    (1,14): ('and never once pauses to explain himself, as if none was needed.', 'and he never once pauses to explain himself at all, as if none was needed.'),
    (1,15): ('So the early church knew this book from the very beginning of all -', 'So the early church clearly knew this book from the very beginning of it all -'),
    (1,16): ('knew it well enough to weave its very words into their own.', 'and knew it well enough to weave its very own words into their own.'),
    (1,17): ('And it leaves one towering question standing over everything else that follows -', 'And it leaves one towering question standing over almost everything else that follows after -'),
    (1,18): ('why was a book this trusted ever buried and left in the dark?', 'why was a book once trusted this much ever buried and left in the dark?'),
    (1,19): ('Look closely now at the sixth chapter of the book of Genesis -', 'Look very closely now at the sixth chapter of the old book of Genesis -'),
    (1,20): ('and there you find the wound this whole book was written to close.', 'and there you find the very wound this whole book was written to finally close.'),
    (1,21): ('The sons of God, the text says, came down and took wives -', 'The sons of God, the old text says, came down and took human wives -'),
    (1,22): ('and giants were born to them there - the mighty men of renown.', 'and great giants were born to them there - the mighty men of old renown.'),
    (1,23): ('And then, right in the middle of the story, Genesis simply stops -', 'And then, right in the very middle of the story, Genesis simply stops short -'),
    (1,24): ('as if you were somehow always meant to already know the rest.', 'as if you yourself were somehow always meant to already know the rest of it.'),
    (1,25): ('The book of Enoch is where the rest was finally written down -', 'The old book of Enoch is where the rest was finally written down at last -'),
    (1,26): ('the whole account that Genesis only brushes past in a single verse.', 'the whole account that the book of Genesis only brushes past in a single verse.'),
    (1,27): ('It opens up an entire lost world from long before the flood -', 'It opens up an entire lost world from long, long before the great flood -'),
    (1,28): ('a vast and ancient world, already tilting hard toward something truly terrible.', 'a vast and ancient world, one that was already tilting toward something truly terrible.'),
    (1,29): ('And the old text insists the ruin did not stop there at all -', 'And the old text firmly insists the ruin did not stop there at all -'),
    (1,30): ('not with the giants alone, and not even on the dry land.', 'not with the towering giants alone, and not even on the dry land itself.'),
    (1,31): ('It reached the beasts of the field and the birds of the air -', 'It reached even the beasts of the field and the wild birds of the air -'),
    (1,32): ('the things that creep upon the ground, and the things that swim below.', 'the things that creep upon the ground, and even the things that swim below.'),
    (1,33): ('Hold on tightly to that very last one of them, just for now -', 'Hold on very tightly to that very last one of them, just for now -'),
    (1,34): ('the things that swim - because almost no one alive ever tells it.', 'the things that swim below - because almost no one alive ever tells of it.'),
    (1,35): ('For now, simply hold tight to what this ancient book opens up -', 'For now, simply hold on tight to what this ancient buried book opens up -'),
    (1,36): ('because the book of Enoch does not begin at all where you expect.', 'because the book of Enoch does not begin at all where you would expect it.'),
    (1,37): ('It does not begin with the flood, or with any water at all -', 'It does not begin with the great flood, or with any water at all -'),
    (1,38): ('and it does not begin inside any walled city built by men.', 'and it does not begin inside any high walled city ever built by men.'),
    (1,39): ('The whole account begins high up on a cold and distant mountain -', 'The whole account begins high up on a cold and far distant mountain peak -'),
    (1,40): ('where, the old book says, two hundred of them once came down.', 'where, the old book says, two full hundred of them once came down together.'),
    (2,1): ('Two hundred of them stood ranged there across the high, snow-locked summit -', 'Two hundred of them stood ranged there across the high, snow-locked mountain summit -'),
    (2,2): ('the old book calls them the Watchers - vast and winged and terrible.', 'the old book calls them the Watchers - vast and winged and utterly terrible.'),
    (2,3): ('They were not sent down at all - they chose to come down themselves.', 'They were not ever sent down at all - they chose to come down all themselves.'),
    (2,4): ('And before they moved at all, they gathered and made a pact.', 'And before they moved at all, they gathered together and made a binding pact.'),
    (2,5): ('An oath, the old text says - one binding each of them to all -', 'An oath, the old text says - one binding each of them to all the rest -'),
    (2,6): ('so that not a single one of them could ever turn back.', 'so that not a single one of them could ever hope to turn back again.'),
    (2,7): ('They swore it upon the cold mountain itself, beneath the open sky -', 'They swore it upon the cold mountain itself, beneath the wide open sky -'),
    (2,8): ('and the pale mountain still carries the very name of that oath.', 'and the pale mountain still carries the very name of that ancient oath.'),
    (2,9): ('This is Mount Hermon - the highest peak of the entire old border -', 'This is Mount Hermon - the highest peak of the entire old northern border -'),
    (2,10): ('snow-crowned, and watching down silently over the whole warm land far below.', 'snow-crowned, and watching down silently over the whole warm land far below it.'),
    (2,11): ('From its white slopes, a single river runs the length of scripture -', 'From its white slopes, a single river runs the whole length of scripture -'),
    (2,12): ('and here, the old text says, the corruption first entered the world.', 'and here, the old text says, the corruption first entered into the world.'),
    (2,13): ('They came down and took human wives for themselves, the account says -', 'They came down and took human wives for themselves, the old account plainly says -'),
    (2,14): ('and taught them dark things that were never meant for the earth.', 'and taught them dark things that were never once meant for the earth.'),
    (2,15): ('The working of metal and blade and fire, the old book says -', 'The working of metal and blade and fire, the old book plainly says -'),
    (2,16): ('and bright secrets the sky above was never supposed to give them.', 'and bright secrets the sky above was never once supposed to give them.'),
    (2,17): ('And from those forbidden unions, the first towering giants were finally born -', 'And from those forbidden unions, the first towering giants were finally born there -'),
    (2,18): ('the mighty men of renown, as the old account itself calls them.', 'the mighty men of renown, as the old account itself plainly calls them.'),
    (2,19): ('They grew far beyond anything the whole earth could ever hope to feed -', 'They grew far beyond anything the whole wide earth could ever hope to feed -'),
    (2,20): ('and when the food ran out at last, they turned on it.', 'and when the food ran out at last, they turned hungrily on it.'),
    (2,21): ('And so the whole wide world tilted down into open, endless violence -', 'And so the whole wide world slowly tilted down into open, endless violence -'),
    (2,22): ('and that is exactly the word the book of Genesis reaches for next.', 'and that is exactly the word the book of Genesis itself reaches for next.'),
    (2,23): ('And the ruin, the old book insists, did not stay on land -', 'And the ruin, the old book insists, did not stay upon the land -'),
    (2,24): ('it reached the beasts, the birds, and even the deep sea itself.', 'it reached the beasts, the birds, and even the deep sea itself below.'),
    (2,25): ('Now hold on tight to the question the old account never answers -', 'Now hold on tight to the question the old account never once answers -'),
    (2,26): ('the giants were all of them sons - the mighty men of renown.', 'the giants were all of them sons - the mighty and the fabled men of renown.'),
    (2,27): ('But if the sons were born, then surely daughters were born too -', 'But if the sons were born, then surely the daughters were born too -'),
    (2,28): ('and yet the old texts spend almost no words at all on them.', 'and yet the old texts spend almost no words at all upon them.'),
    (2,29): ('Genesis names only the warriors here, the mighty and the powerful ones -', 'Genesis names only the warriors here, the mighty ones and the powerful ones -'),
    (2,30): ('and it simply lets the daughters slip quietly out of the story.', 'and it simply lets the daughters slip quietly out of the whole story.'),
    (2,31): ('So what, then, became of them - the daughters lost to the water?', 'So what, then, became of them - the lost daughters given to the water?'),
    (2,32): ('If the sons among them became the towering giants of the land -', 'If the sons among them became the towering giants of the dry land -'),
    (2,33): ('what, then, did the lost daughters become down in the dark water?', 'what, then, did the lost daughters become down in the dark water below?'),
    (2,34): ('Hold on to that one thread - it runs the whole world through.', 'Hold on to that one thread - it runs the whole wide world through.'),
    (2,35): ('Because the great flood, when at last it came, judged the land -', 'Because the great flood, when at last it finally came, judged the land -'),
    (2,36): ('everything that breathed the air and walked upon it was swept away.', 'everything that breathed the air and walked upon it was utterly swept away.'),
    (2,37): ('But water does not ever drown what already lives within the water -', 'But water does not ever drown what already lives within the water itself -'),
    (2,38): ('the deep sea was never threatened - the sea was its own home.', 'the deep sea was never once threatened at all - the sea was its own home.'),
    (2,39): ('And every ocean on the whole earth still remembers something of her -', 'And every ocean on the whole earth still remembers something of her now.'),
    (2,40): ('one same single woman, remembered in a full hundred different human tongues.', 'one and the same single woman, remembered in a full hundred different human tongues.'),
    (3,1): ('Every ocean on the whole wide earth remembers the very same woman -', 'Every ocean on the whole wide earth remembers the very same single woman today -'),
    (3,2): ('and no one alive can quite agree on how that ever happened.', 'and no one alive can quite agree at all on how that ever truly happened.'),
    (3,3): ('Distant peoples who never once met, over oceans they could not cross -', 'Distant peoples who had never once met, over the wide oceans they could not cross -'),
    (3,4): ('each drew the very same figure rising up out of the water.', 'and each one drew the very same figure rising up out of the dark water.'),
    (3,5): ('To know what she really is, go back to before the flood -', 'To know what she really is, go all the way back to before the flood -'),
    (3,6): ('back to the ruin the old book says had by then spread everywhere.', 'back to the ruin the old book says had by that time spread out everywhere.'),
    (3,7): ('The corruption, the book of Enoch says, did not stay in the bloodline -', 'The corruption, the book of Enoch says, did not stay only within the bloodline -'),
    (3,8): ('it reached the beasts, the birds, and the very things that creep -', 'it reached the wild beasts, the birds, and even the very things that creep -'),
    (3,9): ('and the old account adds three short words most retellings quietly skip -', 'and the old account quietly adds three short words that most retellings simply skip -'),
    (3,10): ('the things, the old account says, that swim in the black water.', 'the things, the old account plainly says, that swim down in the black water.'),
    (3,11): ('Then the great flood came at last, just as the book says -', 'Then the great flood came at long last, just exactly as the old book says -'),
    (3,12): ('and swept the whole dark land clean of all that walked it.', 'and swept the whole dark land wholly clean of all that had once walked it.'),
    (3,13): ('But a flood only judges the land - it never judges the deep -', 'But a great flood only judges the land - it never once judges the deep -'),
    (3,14): ('and the deep sea does not drown what already lives in it.', 'and the deep sea itself does not drown what already lives down within it.'),
    (3,15): ('So the old book itself leaves a gap it never once closes -', 'So the old book itself leaves a strange open gap it never once closes -'),
    (3,16): ('a corruption left in the water, and a judgment that missed it.', 'a deep corruption left down in the water, and a judgment that wholly missed it.'),
    (3,17): ('And in that one open gap, the lost daughters at last return -', 'And in that one open gap, the lost daughters at long last quietly return -'),
    (3,18): ('the very ones the old account itself had let slip quietly away.', 'the very ones the old account itself had let slip quietly away before.'),
    (3,19): ('Because the sons of the Watchers became the giants of the land -', 'Because the sons of the Watchers became the towering giants of the dry land -'),
    (3,20): ('and something, the old legends say, rose up out of the water.', 'and something else, the old legends say, rose up out of the dark water.'),
    (3,21): ('Begin with the very oldest of them all - the ancient Greek sirens -', 'Begin with the very oldest of them all - the ancient Greek sea-sirens -'),
    (3,22): ('and throw out entirely the false picture that the movies gave you.', 'and throw out entirely the false picture that all the old movies gave you.'),
    (3,23): ('The very earliest sirens of all had no fish tail at all -', 'The very earliest sirens of all had no fish tail whatsoever at all -'),
    (3,24): ('they were women with the wide wings and talons of a bird.', 'they were women with the wide feathered wings and cruel talons of a bird.'),
    (3,25): ('One thing alone never changed at all across a full thousand years -', 'One thing alone never changed at all across a full thousand long years -'),
    (3,26): ('not the shape of her at all - but always, always the voice.', 'not the outward shape of her at all - but always, always the haunting voice.'),
    (3,27): ('Homer himself wrote of it plainly - the song itself was a weapon -', 'Homer himself wrote of it plainly - the song itself was a deadly weapon -'),
    (3,28): ('and every last sailor who heard it lost all of his will.', 'and every last sailor who ever once heard it lost all of his own will.'),
    (3,29): ('They steered straight on for the music until the hull broke apart -', 'They steered straight on for the music until the wooden hull broke apart -'),
    (3,30): ('a fatal beauty that always ended down in the water, every time.', 'a strange fatal beauty that always ended down in the cold water, every time.'),
    (3,31): ('Then cross the entire wide world to the coast of West Africa -', 'Then cross the entire wide world to the far western coast of West Africa -'),
    (3,32): ('where she is called Mami Wata - which means the mother of water.', 'where she is called Mami Wata - which simply means the mother of water.'),
    (3,33): ('Beautiful, the old traditions all say - yet she is never once safe -', 'Beautiful, the old traditions all say - and yet she is never, ever once safe -'),
    (3,34): ('and she draws men down into a dark world not their own.', 'and she quietly draws helpless men down into a dark world not their own.'),
    (3,35): ('And her worship, even now, is truly no small thing at all -', 'And her worship, even now, is truly no small thing at all today -'),
    (3,36): ('it runs across a whole vast continent, and even crossed the sea.', 'it runs across a whole vast continent, and it even crossed the wide sea.'),
    (3,37): ('Two separate peoples, two far distant oceans, one impossible woman between them -', 'Two separate peoples, two far distant oceans, one impossible woman standing between them -'),
    (3,38): ('and the strange pattern, as we will see, has only just begun.', 'and the strange pattern, as we will soon see, has only just begun.'),
    (3,39): ('How does the whole wide world hold onto the very same memory?', 'How does the whole wide world hold onto the very same single shared memory?'),
    (3,40): ('The answer, it turns out, runs straight back to that cold mountain.', 'The answer, it turns out, runs straight back again to that cold mountain.'),
    (4,2): ('the exact same figure waits on almost every ancient map we have.', 'the exact same figure waits on almost every single ancient map we have.'),
    (4,3): ('Go now to ancient Mesopotamia - the very cradle of the world itself -', 'Go now to ancient Mesopotamia - the very cradle of the whole world itself -'),
    (4,4): ('the very ground where the book of Genesis first begins its story.', 'the very ground where the book of Genesis first begins its whole story.'),
    (4,5): ('The old Babylonians carved her image deep into their ancient temple walls -', 'The old Babylonians carved her image deep into their ancient stone temple walls -'),
    (4,6): ('half a woman and half a fish, from long before the flood.', 'half a woman and half a fish, from long, long before the flood.'),
    (4,7): ('A being that they called Oannes rose up out of the sea -', 'A being that they called Oannes rose up out of the sea itself -'),
    (4,8): ('and taught all of mankind knowledge it was never meant to have.', 'and taught all of mankind knowledge it was never once meant to have.'),
    (4,9): ('And the echo of it is simply impossible to miss at all -', 'And the echo of it here is simply impossible to miss at all -'),
    (4,10): ('for the book of Enoch says the Watchers taught humankind the same.', 'for the book of Enoch says the Watchers taught humankind the very same.'),
    (4,11): ('The very oldest mermaid of them all was, in plain fact, Syrian -', 'The very oldest mermaid of them all was, in plain hard fact, Syrian -'),
    (4,12): ('a full goddess carved in ancient stone and given real worship there.', 'a full goddess carved in ancient stone and given real living worship there.'),
    (4,13): ('This is not the far edge of the map inventing a tale -', 'This is not the far edge of the map inventing some idle tale -'),
    (4,14): ('it is the very heart and center of the whole biblical world.', 'it is the very heart and center of the whole ancient biblical world.'),
    (4,15): ('And past all reason at all, the strange pattern just keeps spreading -', 'And past all reason at all, the strange pattern just keeps on spreading -'),
    (4,16): ('out to far distant peoples who had never heard the name Homer.', 'out to far distant peoples who had never once heard the name Homer.'),
    (4,17): ('Far in the deep Amazon, they know her only as the Iara -', 'Far up the deep Amazon river, they know her only as the Iara -'),
    (4,18): ('the mother of all the water, whose song draws helpless men down.', 'the mother of all the water, whose sweet song draws helpless men down.'),
    (4,19): ('In the cold Slavic rivers, they know her only as the Rusalka -', 'In the cold Slavic rivers, they know her only as the pale Rusalka -'),
    (4,21): ('And in far Japan, they too tell of the Ningyo - a fish-woman -', 'And in far Japan, they too tell of the Ningyo - a strange fish-woman -'),
    (4,22): ('and first written of there, in old Japan, a thousand years ago.', 'and first written of there, in old Japan, a full thousand years ago.'),
    (4,23): ('And on the cold, wet coasts of Ireland, there is the Selkie -', 'And on the cold, wet coasts of Ireland, there is the grey Selkie -'),
    (4,24): ('who sheds her grey sealskin and walks up ashore as a woman.', 'who sheds her grey sealskin and walks up ashore as a full woman.'),
    (4,25): ('But she is always drawn back again, in the end, to the sea -', 'But she is always drawn back again, in the very end, to the sea -'),
    (4,26): ('and always, in the very end, leaving the dry land behind her.', 'and always, in the very end, leaving the dry land behind her forever.'),
    (4,28): ('and all arriving, in the very end, at the very same woman.', 'and all of them arriving, in the very end, at the very same woman.'),
    (4,30): ('and tied always to the deep, dark water - and always the voice.', 'and tied always to the deep, dark water - and always to the voice.'),
    (4,33): ('These far peoples never traded with each other, and never once met -', 'These far peoples never traded with each other, and had never once met -'),
    (4,34): ('yet each one drew the same creature down to the smallest details.', 'yet each one drew the very same creature down to the smallest details.'),
    (4,35): ('A myth always drifts and shifts a little with every single telling -', 'A myth always drifts and shifts a little bit with every single telling -'),
    (4,36): ('but this single one barely moves at all across the whole world.', 'but this single one barely moves at all across the whole wide world.'),
    (4,38): ('the fine line drawn between a mere myth and a real memory.', 'the fine line drawn between a mere passing myth and a real memory.'),
    (4,39): ('And a real memory, they say, always holds fast to its shape -', 'And a real memory, they say, always holds fast tight to its shape -'),
    (4,40): ('because it is truly remembering something that had really once been real.', 'because it is truly remembering something that had really once been fully real.'),
    (5,1): ('Now, before we go any further, the skeptic deserves his full say -', 'Now, before we go any further at all, the skeptic deserves his full say -'),
    (5,2): ('and not the lazy version of it - the strongest one there is.', 'and not the lazy version of it - but the strongest one there is.'),
    (5,3): ('The easy answer is that all people simply share the same fears -', 'The easy answer is that all peoples simply share the very same deep fears -'),
    (5,4): ('water is deeply dangerous, and beauty is always deeply distracting to men.', 'water is deeply dangerous, and beauty is always deeply distracting to most men.'),
    (5,5): ('Put those two simple human fears together, and the argument runs on -', 'Put those two simple human fears together, and the whole argument runs on -'),
    (5,6): ('and any people might dream up a deadly woman in the sea.', 'and almost any people might dream up a deadly woman in the sea.'),
    (5,7): ('Now it is a serious answer - and it does explain the frame -', 'Now it is a serious answer indeed - and it does explain the frame -'),
    (5,8): ('but it strains hard against the detail once you truly examine it.', 'but it strains hard against the fine detail once you truly examine it.'),
    (5,9): ('A shared fear could explain a vague and general resemblance between them -', 'A shared fear could explain a vague and general resemblance between them all -'),
    (5,10): ('but it cannot explain the same woman, down to the finest details.', 'but it cannot ever explain the very same woman, down to the finest details.'),
    (5,11): ('The voice used as a weapon - and not just a pretty sound -', 'The voice used as a weapon - and not just a merely pretty sound -'),
    (5,12): ('the strange pull that overrides a man, instead of merely tempting him.', 'the strange pull that overrides a man, instead of merely gently tempting him.'),
    (5,13): ('The link to the deep sea - not a lake, not the rain -', 'The clear link to the deep sea - not a lake, and not the rain -'),
    (5,14): ('and a fate that proves fatal, every single time, without any fail.', 'and a fate that always proves fatal, every single time, without any fail.'),
    (5,15): ("And then comes the very deepest version of the skeptic's whole case -", "And then comes the very deepest version of the whole skeptic's larger case -"),
    (5,16): ('and it needs no watchers and no giants of any kind at all.', 'and this one needs no watchers and no giants of any kind at all.'),
    (5,17): ('The human mind, it says, carries within it its own inherited shapes -', 'The human mind, it says, carries within it its own deep inherited shapes -'),
    (5,18): ('deep molds that every single one of us is born already holding.', 'deep molds that every single one of us is born already quietly holding.'),
    (5,19): ('On this strange view she rises from within, not from the sea -', 'On this strange view she rises up from deep within, not from the sea -'),
    (5,20): ('the feminine that draws and yet threatens, joined to the deep water.', 'the feminine that draws and yet threatens, forever joined to the deep water.'),
    (5,21): ('By that very same logic, any people at all would draw her -', 'By that very same logic, almost any people at all would draw her -'),
    (5,22): ('not because they ever once saw her - but because they carry her.', 'not because they ever once saw her - but because they all carry her.'),
    (5,23): ('It is an elegant answer, and it is an honest one too -', 'It is an elegant answer indeed, and it is truly an honest one too -'),
    (5,24): ('and it would be truly dishonest of us to just wave it away.', 'and it would be truly dishonest of us to simply wave it away.'),
    (5,25): ('But this one, too, strains right where the fine detail is sharpest -', 'But this one, too, strains hard right where the fine detail is sharpest -'),
    (5,26): ('the voice, the deep dark water, and the fate that never varies.', 'the voice, the deep dark water, and the fixed fate that never varies.'),
    (5,27): ('The archetype explains the wide broad frame that is drawn around her -', 'The archetype explains the wide broad frame that is drawn all around her -'),
    (5,28): ('but it cannot explain the fine precision of the picture inside it.', 'but it cannot ever explain the fine precision of the picture drawn inside it.'),
    (5,29): ('We will not here pretend that either side has been fully proven -', 'We will not here pretend that either side has been at all fully proven -'),
    (5,30): ('only to watch where each is strong, and where each one strains.', 'only to watch closely where each one is strong, and where each one strains.'),
    (5,31): ('And if it truly is a memory - then a memory of what?', 'And if it truly is a memory - then a memory of what exactly?'),
    (5,32): ('and so the question runs straight back to before the flood itself.', 'and so the whole question runs straight back to before the flood itself.'),
    (5,33): ('Back to the one old book that treats her as fully real -', 'Back to the one old book that treats her as something fully real -'),
    (5,34): ('not as mere poetry at all, but as something that truly happened.', 'not as mere poetry at all, but as something that had truly happened.'),
    (5,35): ('And the answer, it turns out, lies hidden within the very words -', 'And the answer, it turns out, lies hidden deep within the very words -'),
    (5,36): ('in a small handful the old translators could never once agree on.', 'in a small handful of them the old translators could never once fully agree on.'),
    (5,37): ('One old word the ancients reached for meant a strange hybrid thing -', 'One old word the ancients reached for meant a strange, mingled hybrid thing -'),
    (5,38): ('a strange being that was never at all fully of this world.', 'a strange being that was never at all fully a part of this world.'),
    (5,39): ('And it appears only where the land lies cursed and emptied out -', 'And it appears only where the land lies cursed and wholly emptied out -'),
    (5,40): ('the place where only things that are not fully human still remain.', 'the place where only the things that are not fully human still remain.'),
    (6,1): ('The clue was never in the stories - it was in the words -', 'The clue was never once in the stories - it was in the words -'),
    (6,2): ('in a small handful the old translators could never once pin down.', 'in a small handful the old translators could never once pin fully down.'),
    (6,3): ('One of them appears in the book of Isaiah - the word lilit -', 'One of them appears in the old book of Isaiah - the word lilit -'),
    (6,4): ('and from that one single word the translations scatter in every direction.', 'and from that one single word the translations scatter off in every direction.'),
    (6,5): ('Some render it as an owl, and some as a night creature -', 'Some render it plainly as an owl, and some as a night creature -'),
    (6,6): ('while still others just gave up and left it wholly untranslated there.', 'while still others just gave up and left it wholly untranslated right there.'),
    (6,7): ('But the very oldest Greek version of all chose a different word -', 'But the very oldest Greek version of all chose a wholly different word -'),
    (6,10): ('in some cursed and emptied out land, long after the great judgment.', 'in some cursed and emptied out land, long after the great final judgment.'),
    (6,11): ('The place where only things not fully human are left to remain -', 'The place where only the things not fully human are left to remain -'),
    (6,13): ('And around that one single word, a whole figure slowly grew up -', 'And around that one single word, a whole strange figure slowly grew up -'),
    (6,16): ('translated as dragon in one place, sea monster in the very next.', 'translated as dragon in one place, and sea monster in the very next.'),
    (6,17): ('And here, at very long last, is where the point turns sharp -', 'And here, at very long last, is where the whole point turns sharp -'),
    (6,18): ('the great flood judged the land, but the sea stayed beyond it.', 'the great flood judged the land, but the sea stayed well beyond it.'),
    (6,19): ('It is in the book of Job this gets its fullest voice -', 'It is in the old book of Job this gets its very fullest voice -'),
    (6,21): ('A vast creature of the deep that no weapon can ever wound -', 'A vast creature of the deep that no weapon can ever hope to wound -'),
    (6,22): ('one that breathes out fire, and dwells where all light gives out.', 'one that breathes out fire, and dwells where all light finally gives out.'),
    (6,23): ('And the most striking thing of all is who speaks of it -', 'And the most striking thing of all is exactly who speaks of it -'),
    (6,24): ('not some poet, but God himself, as a real and present thing.', 'not some poet, but God himself, as a real and present living thing.'),
    (6,25): ('For the ancient writer, the wide sea was never just plain water -', 'For the ancient writer, the wide sea was never once just plain water -'),
    (6,26): ('it was the deep - the very place order never fully reached below.', 'it was the deep - the very place order never fully reached down below.'),
    (6,27): ('The book of Genesis itself says it in its very second breath -', 'The book of Genesis itself says it in its very second opening breath -'),
    (6,28): ('darkness over the face of the deep water, before all else came.', 'darkness over the face of the deep water, before all else once came.'),
    (6,29): ('And still other lines name a monster the sea yet still holds -', 'And still other lines name a great monster the sea yet still holds -'),
    (6,30): ('a raw chaos the divine hand once had to press back down.', 'a raw chaos the divine hand once had to press firmly back down.'),
    (6,31): ('The old world clearly knew what lived down in the deep places -', 'The old world clearly knew what lived down in the deep dark places -'),
    (6,32): ('a deep knowledge that we ourselves have since lost almost completely now.', 'a deep knowledge that we ourselves have since lost almost wholly completely now.'),
    (6,33): ('And they wrote every bit of it down, not as mere legend -', 'And they wrote every last bit of it down, not as mere legend -'),
    (6,34): ('but as sober plain fact, in the very plainest words they had.', 'but as sober plain fact, in the very plainest words that they had.'),
    (6,35): ('So the very words themselves keep pointing us all in one direction -', 'So the very words themselves keep pointing us all in one single direction -'),
    (6,36): ('back to the deep, and back to what the flood never touched.', 'back to the deep, and back to what the great flood never once touched.'),
    (6,37): ('A deep corruption that had reached down, at last, into the water -', 'A deep corruption that had reached down, at long last, into the water -'),
    (6,38): ('and a judgment that fell, in the end, only upon the land.', 'and a judgment that fell, in the very end, only upon the land.'),
    (6,39): ('Two plain facts, the old book leaves standing there side by side -', 'Two plain hard facts, the old book leaves standing there side by side -'),
    (6,40): ('and in the narrow space left between them, she still lives on.', 'and in the narrow space left between them, she still quietly lives on.'),
    (7,1): ('Now, at long last, set the whole thing down carefully into order -', 'Now, at very long last, set the whole thing carefully down into order -'),
    (7,2): ('because it is only when the picture lines up that it holds.', 'because it is only when the whole picture lines up that it truly holds.'),
    (7,3): ('The Watchers first came down, all of them drawn by human women -', 'The Watchers first came down, all of them drawn down by human women -'),
    (7,4): ('and from them the great giants were born, the men of renown.', 'and from them the great giants were born, the mighty men of renown.'),
    (7,5): ('But now watch closely the strange shape of it - the symmetry itself -', 'But now watch closely the strange shape of it - the deep symmetry itself -'),
    (7,6): ('for the symmetry of it is the truly unsettling part of all.', 'for the strange symmetry of it is the truly and deeply unsettling part of all.'),
    (7,7): ('The great fathers first came down, down through the human women below -', 'The great fathers first came down, down through the human women far below -'),
    (7,8): ('a descent - down out of the high sky, into the world below.', 'a great descent - down and out of the high sky, into the world far below.'),
    (7,9): ('And the reflection of it, the legends say, rose the other way -', 'And the reflection of it, the old legends say, rose the other way -'),
    (7,10): ('up through the men - an ascent, up out of the deep water.', 'up through the men below - an ascent, up out of the deep dark water.'),
    (7,11): ('The daughters carried within them the very same nature as the sons -', 'The daughters carried deep within them the very same nature as the sons -'),
    (7,12): ('and turned it on men, as the sons turned it on the world.', 'and turned it hard on men, as the sons turned it on the world.'),
    (7,13): ('The one of them came down, down through the wide open sky -', 'The one of them came down, down through the wide and open sky -'),
    (7,14): ('and the other one rose up, up through the deep dark sea.', 'and the other one rose up, up through the deep and dark sea.'),
    (7,15): ('The old book, remember, says the Bible itself does not close it -', 'The old book, remember, says the Bible itself does not ever close it -'),
    (7,16): ('it names no single verse that follows her down into the deep.', 'it names no single verse that follows her down into the dark deep.'),
    (7,17): ('What it gives us instead is a far stranger fact than that -', 'What it gives us instead is a far stranger fact than even that -'),
    (7,18): ('the great flood was meant to end them - and yet did not.', 'the great flood was meant to fully end them - and yet did not.'),
    (7,19): ('Because the giants themselves come right back, even after the great water -', 'Because the great giants themselves come right back, even long after the water -'),
    (7,20): ('whole peoples of them, each one with their own names and lands.', 'whole peoples of them, each one with their own strange names and their own lands.'),
    (7,21): ('The spies that Moses sent out came back utterly terrified of them -', 'The spies that Moses sent out came back utterly terrified of them all -'),
    (7,22): ('we were like mere grasshoppers, they said, when standing there before them.', 'we were like mere grasshoppers, they said, when standing there before them all.'),
    (7,24): ('It was Og of Bashan - the very last of a giant line.', 'It was Og of Bashan - the very last of an ancient giant line.'),
    (7,25): ('The old book does something here that is almost forensic in nature -', 'The old book does something here that is almost forensic in its nature -'),
    (7,26): ('it carefully records the sheer size of his great black iron bed.', 'it carefully records the sheer great size of his huge black iron bed.'),
    (7,27): ('It stretched more than four whole meters in length, that iron bed -', 'It stretched more than four whole meters in length, that great iron bed -'),
    (7,28): ('as if some scribe had wanted to prove it was no tale.', 'as if some careful scribe had wanted to prove it was no tale.'),
    (7,29): ('And this was fully a thousand years after the great flood itself -', 'And this was fully a thousand years after the great flood itself had passed -'),
    (7,30): ('long after the flood water should, by rights, have erased them all.', 'long after the great flood water should, by every right, have erased them all.'),
    (7,31): ('And somehow, that which should have vanished had come back once more -', 'And somehow, that which should have wholly vanished had come back once more -'),
    (7,32): ('and not as a legend, but as real flesh, bone, and iron.', 'and not as a mere legend, but as real flesh, bone, and iron.'),
    (7,33): ('The old text does not even try to explain how at all -', 'The old text does not even once try to explain how at all -'),
    (7,34): ('it simply records the plain hard fact, and then moves quietly on.', 'it simply records the plain hard fact, and then quietly moves along on.'),
    (7,35): ('Leaving the whole plain contradiction just sitting right there upon the page -', 'Leaving the whole plain contradiction just sitting right there upon the open page -'),
    (7,36): ('for anyone at all who still has the eyes to notice it.', 'for anyone at all who still has the eyes left to notice it.'),
    (7,37): ('If the sons of them somehow survived the water on the land -', 'If the sons of them somehow survived the great water on the land -'),
    (7,38): ('then what survived it all, the old legends ask, in the sea?', 'then what survived it all, the old legends ask, out there in the sea?'),
    (7,39): ('And now, at last, the story is very nearly whole and complete -', 'And now, at long last, the story is very nearly whole and complete -'),
    (7,40): ('and it ends, of all the places, out at the open sea.', 'and it ends, of all the places, far out at the open sea.'),
    (8,1): ('The whole story is nearly complete - and it ends at the sea.', 'The whole story is very nearly complete - and it ends out at the sea.'),
    (8,2): ('Turn now, then, to the very last book of the whole Bible.', 'Turn now, then, to the very last book of the whole entire Christian Bible.'),
    (8,3): ('John writes of a whole new heaven and a whole new earth -', 'John writes there of a whole new heaven and of a whole new earth -'),
    (8,4): ('and the first old heaven and the first earth had passed away.', 'and the first old heaven and the first old earth had wholly passed away.'),
    (8,5): ('And then he adds four small words almost no one pauses on -', 'And then he adds four small words that almost no one ever once pauses on -'),
    (8,6): ('and then he says it quite plainly - the sea was no more.', 'and then he says it quite plainly - the sea itself was now no more.'),
    (8,7): ('Of every single thing that he could have named as finally gone -', 'Of every single thing that he could ever have named as being finally gone -'),
    (8,8): ('no more death at all, no more pain, and no more tears -', 'no more death at all, no more pain, and no more bitter tears -'),
    (8,9): ('he makes a real point of saying that the sea is gone.', 'he makes a real point of saying that the sea itself is finally gone.'),
    (8,10): ('But why the sea? Why would that stand among the great promises?', 'But why the sea? Why would that ever stand there among the great promises?'),
    (8,11): ('Because in the old texts the sea itself was never only water -', 'Because in the old texts the sea itself was never once merely only water -'),
    (8,12): ('it was the deep, the abyss - the place order never once reached.', 'it was the deep, the abyss - the place order never once truly reached.'),
    (8,13): ('John himself writes it from his exile, alone on a far island -', 'John himself writes it from his own bitter exile, alone on a far island -'),
    (8,14): ('ringed on every side by the very sea he says will end.', 'ringed on every single side by the very sea that he says will end.'),
    (8,15): ('If the sea itself holds the memory of what came long before -', 'If the sea itself holds the deep memory of what had come long before -'),
    (8,16): ('then its ending is not weather at all, and not mere geography.', 'then its ending is not weather at all, and not mere plain geography either.'),
    (8,17): ('It is a door, the old readers say, at last finally closing -', 'It is a great door, the old readers say, at long last finally closing -'),
    (8,18): ('a great door that had stood open since the days of Noah.', 'a great door that had stood wide open ever since the far days of Noah.'),
    (8,19): ('Since the day the Watchers came, and since the giants themselves came -', 'Since the very day the Watchers came, and since the giants themselves came -'),
    (8,20): ('and since the daughters, too, who all went down into the water.', 'and since the daughters, too, who all went down deep into the dark water.'),
    (8,21): ('Ever since the sirens who sang out on their bright, windy sea-cliffs -', 'Ever since the sirens who sang out on their bright and windy sea-cliffs -'),
    (8,22): ('since Mami Wata, who is mother of all the West African rivers -', 'since Mami Wata, who is the great mother of all the West African rivers -'),
    (8,23): ('since Atargatis, the old goddess carved long ago in pale Syrian stone -', 'since Atargatis, the old fish-goddess carved long ago in pale Syrian stone -'),
    (8,24): ('since Oannes, who rose up from the sea to teach the Babylonians -', 'since Oannes, who rose up out of the sea to teach the ancient Babylonians -'),
    (8,25): ('since the Iara, still singing far out upon the great Amazon river -', 'since the Iara, still singing far out upon the great green Amazon river -'),
    (8,26): ('since the pale Rusalka, and even since the far-off Japanese Ningyo too -', 'since the pale Rusalka, and even since the far-off and strange Japanese Ningyo too -'),
    (8,27): ('since the Selkie out upon the cold and bright northern Irish coasts -', 'since the grey Selkie out upon the cold and bright northern Irish sea-coasts -'),
    (8,28): ('the water spirits, every one of them, of a hundred scattered cultures.', 'the water spirits, every single one of them, of a full hundred scattered cultures.'),
    (8,29): ('A whole hundred peoples who had never even once known one another -', 'A whole hundred peoples who had never even once known of one single another -'),
    (8,30): ('and yet who all, somehow, still remembered the very same single woman.', 'and yet who all, somehow, still remembered the very same single haunting woman.'),
    (8,31): ('She is always feminine, and yet always far more than merely human -', 'She is always feminine, and yet always far more than merely human at all now -'),
    (8,32): ('and tied always to the deep water - and always, always the voice.', 'and tied always to the deep water - and always, always to the voice.'),
    (8,33): ('We do not ask you here to close off the question at all -', 'We do not ask you here to fully close off the whole question at all -'),
    (8,34): ('only to feel the sheer weight of what gathers, page by page.', 'only to feel the sheer heavy weight of what gathers, page by page.'),
    (8,35): ('The old texts describe her - we do not claim to prove her -', 'The old texts describe her - we do not ever claim to prove her -'),
    (8,36): ('because an absent verse is never the same as truly absent evidence.', 'because an absent verse is never quite the same thing as truly absent evidence.'),
    (8,37): ('And what gathers here, culture after culture, is hard to set down -', 'And what gathers here, culture after culture, is genuinely hard to set down -'),
    (8,38): ('it is always the same woman, the same water, the same call.', 'it is always the same woman, the same dark water, the same haunting call.'),
    (8,39): ('The sea, John promises, will one day be no more at all -', 'The sea, John promises, will one day soon be no more at all -'),
    (8,40): ('and this was only one of the things the buried book remembered.', 'and this was only one of the things the old buried book remembered.'),
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default="master.csv")
    a = ap.parse_args()
    path = a.csv
    if not os.path.isfile(path):
        sys.stderr.write("ERROR: not found: %s\n" % path); sys.exit(1)
    with open(path, newline="", encoding="utf-8") as f:
        rd = csv.DictReader(f); fields = rd.fieldnames; rows = list(rd)
    for col in ("block_id", "clip_index", "narration"):
        if col not in fields:
            sys.stderr.write("ERROR: master.csv missing column %s\n" % col); sys.exit(1)
    seen = set(); applied = skipped = 0; mism = []
    for r in rows:
        try:
            key = (int(r["block_id"]), int(r["clip_index"]))
        except (ValueError, KeyError):
            continue
        if key not in EDITS:
            continue
        seen.add(key); old, nw = EDITS[key]; cur = r["narration"]
        if cur == nw: skipped += 1
        elif cur == old: r["narration"] = nw; applied += 1
        else: mism.append((key, cur))
    missing = sorted(set(EDITS) - seen)
    if missing:
        sys.stderr.write("ERROR: %d edit keys not in master: %s\n" % (len(missing), ", ".join("%d/%d" % k for k in missing[:10]))); sys.exit(1)
    if mism:
        sys.stderr.write("ERROR: %d anchor mismatches -- ABORT (no write). Source drifted from pass-2.\n" % len(mism))
        for k, c in mism[:5]: sys.stderr.write("  %d/%d current: %r\n" % (k[0], k[1], c[:70]))
        sys.exit(1)
    if applied == 0:
        print("no changes (all %d beats already at pass-3 lines)" % skipped); return
    bak = path + ".pre_p3fill"
    if not os.path.exists(bak):
        with open(bak, "w", encoding="utf-8") as b, open(path, encoding="utf-8") as o: b.write(o.read())
        print("backup:", bak)
    with open(path, "w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields); w.writeheader(); w.writerows(rows)
    print("OK: pass-3 container fill applied. beats changed: %d | already-done: %d" % (applied, skipped))


if __name__ == "__main__":
    main()
